"""init migration

Revision ID: 988f1a212819
Revises: 1e721a446ef6
Create Date: 2018-05-22 20:38:44.803956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988f1a212819'
down_revision = '1e721a446ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
